disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - line_length
    - function_parameter_count
    - unused_closure_parameter
opt_in_rules: # some rules are only opt-in
    - force_unwrapping
    - empty_count
# Find all the available rules by running:
# swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
    - ../Squircle

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - ../Example
#   - Source/ExcludedFolder
#   - Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
# force_cast: warning # implicitly
# force_try:
#     severity: warning # explicitly

## rules that have both warning and error levels, can set just the warning level
## implicitly
line_length:
    warning: 175
    error: 220

## they can set both implicitly with an array
#type_body_length:
#	- 300 # warning
#	- 400 # error

# or they can set both explicitly
file_length:
    warning: 800
    error: 1200

## naming rules can set warnings/errors for min_length and max_length
## additionally they can set excluded names
#type_name:
#min_length: 4 # only warning
#max_length: # warning and error
#warning: 40
#error: 50
#excluded: iPhone # excluded via string
#variable_name:
#min_length: # only min_length
#error: 4 # only error
#excluded: # excluded via string array
#	- id
#	- URL
#	- GlobalAPIKey
#reporter: "csv" # reporter type (xcode, json, csv, checkstyle)
identifier_name:
    min_length: 2
    max_length: 50

type_name:
    max_length:
      warning: 50
      error: 60
    min_length:
        warning: 1

type_body_length:
    warning: 250

function_body_length:
    warning: 70

custom_rules:
    enum_force_cast: # rule identifier
        name: "Enum force Cast" # rule name. optional.
        regex: '\(rawValue: [a-zA-Z]*\)\!' # matching pattern
        # match_kinds: # SyntaxKinds to match. optional.
        #     - comment
        #     - identifier
        message: "Enum force Cast." # violation message. optional.
        # match_kinds: string
